# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\x07library\"Z\n\x05Staff\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x16\n\tfull_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_full_name\"j\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x16\n\tfull_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_full_name\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"9\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\"\x17\n\x15GetCurrentUserRequest2\xbd\x01\n\x0b\x41uthService\x12\x34\n\x08Register\x12\x18.library.RegisterRequest\x1a\x0e.library.Staff\x12\x36\n\x05Login\x12\x15.library.LoginRequest\x1a\x16.library.LoginResponse\x12@\n\x0eGetCurrentUser\x12\x1e.library.GetCurrentUserRequest\x1a\x0e.library.Staffb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STAFF']._serialized_start=30
  _globals['_STAFF']._serialized_end=120
  _globals['_REGISTERREQUEST']._serialized_start=122
  _globals['_REGISTERREQUEST']._serialized_end=228
  _globals['_LOGINREQUEST']._serialized_start=230
  _globals['_LOGINREQUEST']._serialized_end=277
  _globals['_LOGINRESPONSE']._serialized_start=279
  _globals['_LOGINRESPONSE']._serialized_end=336
  _globals['_GETCURRENTUSERREQUEST']._serialized_start=338
  _globals['_GETCURRENTUSERREQUEST']._serialized_end=361
  _globals['_AUTHSERVICE']._serialized_start=364
  _globals['_AUTHSERVICE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
