# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import books_pb2 as protos_dot_books__pb2
from protos import common_pb2 as protos_dot_common__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/books_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """============================================
    SERVICE DEFINITION (RPC Methods)
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBooks = channel.unary_unary(
                '/library.BookService/GetBooks',
                request_serializer=protos_dot_books__pb2.GetBooksRequest.SerializeToString,
                response_deserializer=protos_dot_books__pb2.GetBooksResponse.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/library.BookService/GetBook',
                request_serializer=protos_dot_books__pb2.GetBookRequest.SerializeToString,
                response_deserializer=protos_dot_books__pb2.Book.FromString,
                _registered_method=True)
        self.CreateBook = channel.unary_unary(
                '/library.BookService/CreateBook',
                request_serializer=protos_dot_books__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=protos_dot_books__pb2.Book.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.BookService/UpdateBook',
                request_serializer=protos_dot_books__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=protos_dot_books__pb2.Book.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/library.BookService/DeleteBook',
                request_serializer=protos_dot_books__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=protos_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """============================================
    SERVICE DEFINITION (RPC Methods)
    ============================================

    """

    def GetBooks(self, request, context):
        """Get all books (with optional filters)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Get a single book by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBook(self, request, context):
        """Create a new book
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Update an existing book
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Delete a book
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooks,
                    request_deserializer=protos_dot_books__pb2.GetBooksRequest.FromString,
                    response_serializer=protos_dot_books__pb2.GetBooksResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=protos_dot_books__pb2.GetBookRequest.FromString,
                    response_serializer=protos_dot_books__pb2.Book.SerializeToString,
            ),
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=protos_dot_books__pb2.CreateBookRequest.FromString,
                    response_serializer=protos_dot_books__pb2.Book.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=protos_dot_books__pb2.UpdateBookRequest.FromString,
                    response_serializer=protos_dot_books__pb2.Book.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=protos_dot_books__pb2.DeleteBookRequest.FromString,
                    response_serializer=protos_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """============================================
    SERVICE DEFINITION (RPC Methods)
    ============================================

    """

    @staticmethod
    def GetBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/GetBooks',
            protos_dot_books__pb2.GetBooksRequest.SerializeToString,
            protos_dot_books__pb2.GetBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/GetBook',
            protos_dot_books__pb2.GetBookRequest.SerializeToString,
            protos_dot_books__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/CreateBook',
            protos_dot_books__pb2.CreateBookRequest.SerializeToString,
            protos_dot_books__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/UpdateBook',
            protos_dot_books__pb2.UpdateBookRequest.SerializeToString,
            protos_dot_books__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BookService/DeleteBook',
            protos_dot_books__pb2.DeleteBookRequest.SerializeToString,
            protos_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
