# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import borrowings_pb2 as protos_dot_borrowings__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/borrowings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BorrowingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBorrowingsHistory = channel.unary_unary(
                '/library.BorrowingService/GetBorrowingsHistory',
                request_serializer=protos_dot_borrowings__pb2.GetBorrowRequest.SerializeToString,
                response_deserializer=protos_dot_borrowings__pb2.GetBorrowingsResponse.FromString,
                _registered_method=True)
        self.GetCurrentBorrowings = channel.unary_unary(
                '/library.BorrowingService/GetCurrentBorrowings',
                request_serializer=protos_dot_borrowings__pb2.GetBorrowRequest.SerializeToString,
                response_deserializer=protos_dot_borrowings__pb2.GetBorrowingsResponse.FromString,
                _registered_method=True)
        self.GetMemberBorrowings = channel.unary_unary(
                '/library.BorrowingService/GetMemberBorrowings',
                request_serializer=protos_dot_borrowings__pb2.GetMemberBorrowingsRequest.SerializeToString,
                response_deserializer=protos_dot_borrowings__pb2.GetBorrowingsResponse.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.BorrowingService/BorrowBook',
                request_serializer=protos_dot_borrowings__pb2.BorrowRequest.SerializeToString,
                response_deserializer=protos_dot_borrowings__pb2.BorrowResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.BorrowingService/ReturnBook',
                request_serializer=protos_dot_borrowings__pb2.ReturnRequest.SerializeToString,
                response_deserializer=protos_dot_borrowings__pb2.ReturnResponse.FromString,
                _registered_method=True)


class BorrowingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBorrowingsHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentBorrowings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemberBorrowings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BorrowingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBorrowingsHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBorrowingsHistory,
                    request_deserializer=protos_dot_borrowings__pb2.GetBorrowRequest.FromString,
                    response_serializer=protos_dot_borrowings__pb2.GetBorrowingsResponse.SerializeToString,
            ),
            'GetCurrentBorrowings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentBorrowings,
                    request_deserializer=protos_dot_borrowings__pb2.GetBorrowRequest.FromString,
                    response_serializer=protos_dot_borrowings__pb2.GetBorrowingsResponse.SerializeToString,
            ),
            'GetMemberBorrowings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemberBorrowings,
                    request_deserializer=protos_dot_borrowings__pb2.GetMemberBorrowingsRequest.FromString,
                    response_serializer=protos_dot_borrowings__pb2.GetBorrowingsResponse.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=protos_dot_borrowings__pb2.BorrowRequest.FromString,
                    response_serializer=protos_dot_borrowings__pb2.BorrowResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=protos_dot_borrowings__pb2.ReturnRequest.FromString,
                    response_serializer=protos_dot_borrowings__pb2.ReturnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.BorrowingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.BorrowingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BorrowingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBorrowingsHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BorrowingService/GetBorrowingsHistory',
            protos_dot_borrowings__pb2.GetBorrowRequest.SerializeToString,
            protos_dot_borrowings__pb2.GetBorrowingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentBorrowings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BorrowingService/GetCurrentBorrowings',
            protos_dot_borrowings__pb2.GetBorrowRequest.SerializeToString,
            protos_dot_borrowings__pb2.GetBorrowingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemberBorrowings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BorrowingService/GetMemberBorrowings',
            protos_dot_borrowings__pb2.GetMemberBorrowingsRequest.SerializeToString,
            protos_dot_borrowings__pb2.GetBorrowingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BorrowingService/BorrowBook',
            protos_dot_borrowings__pb2.BorrowRequest.SerializeToString,
            protos_dot_borrowings__pb2.BorrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.BorrowingService/ReturnBook',
            protos_dot_borrowings__pb2.ReturnRequest.SerializeToString,
            protos_dot_borrowings__pb2.ReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
