# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/members.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/members.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protos import common_pb2 as protos_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/members.proto\x12\x07library\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13protos/common.proto\"\xbd\x01\n\x06Member\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\x05phone\x18\x04 \x01(\tH\x01\x88\x01\x01\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x07\n\x05_nameB\x08\n\x06_phone\"^\n\x13\x43reateMemberRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\x05phone\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_phone\"[\n\x13UpdateMemberRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05phone\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_phone\"!\n\x13\x44\x65leteMemberRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"6\n\x12GetMembersResponse\x12 \n\x07members\x18\x01 \x03(\x0b\x32\x0f.library.Member\"\x1e\n\x10GetMemberRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x13\n\x11GetMembersRequest2\xcb\x02\n\rMemberService\x12\x45\n\nGetMembers\x12\x1a.library.GetMembersRequest\x1a\x1b.library.GetMembersResponse\x12\x37\n\tGetMember\x12\x19.library.GetMemberRequest\x1a\x0f.library.Member\x12=\n\x0c\x43reateMember\x12\x1c.library.CreateMemberRequest\x1a\x0f.library.Member\x12=\n\x0cUpdateMember\x12\x1c.library.UpdateMemberRequest\x1a\x0f.library.Member\x12<\n\x0c\x44\x65leteMember\x12\x1c.library.DeleteMemberRequest\x1a\x0e.library.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.members_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBER']._serialized_start=88
  _globals['_MEMBER']._serialized_end=277
  _globals['_CREATEMEMBERREQUEST']._serialized_start=279
  _globals['_CREATEMEMBERREQUEST']._serialized_end=373
  _globals['_UPDATEMEMBERREQUEST']._serialized_start=375
  _globals['_UPDATEMEMBERREQUEST']._serialized_end=466
  _globals['_DELETEMEMBERREQUEST']._serialized_start=468
  _globals['_DELETEMEMBERREQUEST']._serialized_end=501
  _globals['_GETMEMBERSRESPONSE']._serialized_start=503
  _globals['_GETMEMBERSRESPONSE']._serialized_end=557
  _globals['_GETMEMBERREQUEST']._serialized_start=559
  _globals['_GETMEMBERREQUEST']._serialized_end=589
  _globals['_GETMEMBERSREQUEST']._serialized_start=591
  _globals['_GETMEMBERSREQUEST']._serialized_end=610
  _globals['_MEMBERSERVICE']._serialized_start=613
  _globals['_MEMBERSERVICE']._serialized_end=944
# @@protoc_insertion_point(module_scope)
