# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import common_pb2 as protos_dot_common__pb2
from protos import members_pb2 as protos_dot_members__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/members_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemberServiceStub(object):
    """============================================
    SERVICE DEFINITION (RPC Methods)
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMembers = channel.unary_unary(
                '/library.MemberService/GetMembers',
                request_serializer=protos_dot_members__pb2.GetMembersRequest.SerializeToString,
                response_deserializer=protos_dot_members__pb2.GetMembersResponse.FromString,
                _registered_method=True)
        self.GetMember = channel.unary_unary(
                '/library.MemberService/GetMember',
                request_serializer=protos_dot_members__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=protos_dot_members__pb2.Member.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/library.MemberService/CreateMember',
                request_serializer=protos_dot_members__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=protos_dot_members__pb2.Member.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library.MemberService/UpdateMember',
                request_serializer=protos_dot_members__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=protos_dot_members__pb2.Member.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/library.MemberService/DeleteMember',
                request_serializer=protos_dot_members__pb2.DeleteMemberRequest.SerializeToString,
                response_deserializer=protos_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class MemberServiceServicer(object):
    """============================================
    SERVICE DEFINITION (RPC Methods)
    ============================================

    """

    def GetMembers(self, request, context):
        """Get all members
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMember(self, request, context):
        """Get member by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Create a new member
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Update a member
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Delete a member
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMembers,
                    request_deserializer=protos_dot_members__pb2.GetMembersRequest.FromString,
                    response_serializer=protos_dot_members__pb2.GetMembersResponse.SerializeToString,
            ),
            'GetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMember,
                    request_deserializer=protos_dot_members__pb2.GetMemberRequest.FromString,
                    response_serializer=protos_dot_members__pb2.Member.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=protos_dot_members__pb2.CreateMemberRequest.FromString,
                    response_serializer=protos_dot_members__pb2.Member.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=protos_dot_members__pb2.UpdateMemberRequest.FromString,
                    response_serializer=protos_dot_members__pb2.Member.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=protos_dot_members__pb2.DeleteMemberRequest.FromString,
                    response_serializer=protos_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.MemberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.MemberService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemberService(object):
    """============================================
    SERVICE DEFINITION (RPC Methods)
    ============================================

    """

    @staticmethod
    def GetMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.MemberService/GetMembers',
            protos_dot_members__pb2.GetMembersRequest.SerializeToString,
            protos_dot_members__pb2.GetMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.MemberService/GetMember',
            protos_dot_members__pb2.GetMemberRequest.SerializeToString,
            protos_dot_members__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.MemberService/CreateMember',
            protos_dot_members__pb2.CreateMemberRequest.SerializeToString,
            protos_dot_members__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.MemberService/UpdateMember',
            protos_dot_members__pb2.UpdateMemberRequest.SerializeToString,
            protos_dot_members__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.MemberService/DeleteMember',
            protos_dot_members__pb2.DeleteMemberRequest.SerializeToString,
            protos_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
